# MM-CT-DAS System Configuration
system:
  name: "MM-CT-DAS"
  version: "1.0.0"
  debug: false

# Network monitoring configuration
network:
  interface: "auto"  # Auto-detect or specify interface name
  capture_filter: ""  # BPF filter for packet capture
  packet_buffer_size: 10000

# Threat detection configuration  
detection:
  ml_models_path: "models/"
  yara_rules_path: "config/yara_rules/"
  threat_threshold: 0.7
  enable_realtime: true

# Database configuration
database:
  type: "sqlite"
  path: "data/threats.db"
  max_connections: 10

# Dashboard configuration
dashboard:
  port: 8501
  host: "localhost"
  refresh_interval: 5

# Response configuration
response:
  auto_block: false  # Enable automatic IP blocking
  firewall_integration: true
  email_notifications: false
  log_all_events: true

# Logging configuration
logging:
  level: "INFO"
  max_file_size: "10MB"
  backup_count: 5